"""`runspace init <tenant-id>` — scaffold a new tenant."""

from __future__ import annotations

import sys
from pathlib import Path
from textwrap import dedent


def run_init(
    *,
    tenant_id: str,
    target_dir: Path,
    name: str | None = None,
    icon: str = "🗂",
    brand_color: str = "#3B82F6",
    interactive: bool = True,
) -> int:
    """Scaffold tenants/<tenant_id>/ under target_dir."""

    if not _valid_tenant_id(tenant_id):
        print(
            f"ERROR: tenant_id {tenant_id!r} must be lowercase letters/digits/-, "
            f"start with a letter, length 1–32",
            file=sys.stderr,
        )
        return 2

    tenant_dir = target_dir / "tenants" / tenant_id
    if tenant_dir.exists():
        print(f"ERROR: {tenant_dir} already exists — refusing to overwrite", file=sys.stderr)
        return 3

    # Every prompt already shows the value it will use, so a closed stdin —
    # CI, a Dockerfile, `runspace init x < /dev/null` — takes the default
    # rather than crashing with an unhandled EOFError half-scaffolded.
    def ask(prompt: str) -> str:
        try:
            return input(prompt).strip()
        except EOFError:
            print("(no input available — using the default)", file=sys.stderr)
            return ""

    if interactive and not name:
        name = ask(f"Display name for {tenant_id} [{tenant_id.replace('-', ' ').title()}]: ")
    name = name or tenant_id.replace("-", " ").title()

    if interactive:
        ans = ask(f"Brand color [{brand_color}]: ")
        if ans:
            brand_color = ans
        ans = ask(f"Workspace icon (emoji) [{icon}]: ")
        if ans:
            icon = ans

    tenant_dir.mkdir(parents=True)
    (tenant_dir / "agents").mkdir()
    (tenant_dir / "plugins").mkdir()

    _write(tenant_dir / "workspace.yml", _workspace_yml(tenant_id, name, icon, brand_color))
    _write(tenant_dir / "config.yaml", _config_yaml())
    _write(tenant_dir / "routines.yml", _routines_yml())
    _write(tenant_dir / "plugins" / "__init__.py", "")
    _write(tenant_dir / "plugins" / "health.py", _example_plugin_health())
    _write(tenant_dir / ".npmrc", _npmrc())
    _write(tenant_dir / "Dockerfile", _dockerfile(tenant_id))
    _write(tenant_dir / "docker-compose.yml", _docker_compose(tenant_id))
    _write(tenant_dir / "README.md", _readme(tenant_id, name))

    print(f"\n✅ tenant scaffolded at {tenant_dir}\n")
    print("Next steps:")
    print(f"  cd {tenant_dir}")
    print("  # Add your agents under agents/<role>/SOUL.md + tools/")
    print("  # Edit workspace.yml plugins: list as you add plugin modules")
    print("  python -m runspace.workspace.serve workspace.yml   # local boot")
    print("  docker compose up                                    # docker boot")
    return 0


# ─────────────────────────────────────────────────────────────────
# helpers
# ─────────────────────────────────────────────────────────────────


def _valid_tenant_id(s: str) -> bool:
    import re

    return bool(re.fullmatch(r"[a-z][a-z0-9-]{0,31}", s))


def _write(p: Path, content: str) -> None:
    p.write_text(content)


def _workspace_yml(tenant_id: str, name: str, icon: str, brand_color: str) -> str:
    return dedent(f"""\
        # {name} — workspace configuration
        # Generated by `runspace init {tenant_id}`.

        name: "{name}"
        icon: "{icon}"
        brand_color: "{brand_color}"
        sidebar_color: "#1F2937"

        # ── LLM provider ─────────────────────────────────────────────────
        # Default to Router; override per-agent via apps.<id>.model
        # if you need a different one.
        providers:
          router:
            base_url: https://router.example.com/v1
            api_key: ${{AI_API_KEY}}

        # ── Users (workspace seats) ──────────────────────────────────────
        users:
          owner:
            name: Owner
            role: Owner
            avatar: O
            default: true

        # ── Channels (sidebar UI) ────────────────────────────────────────
        channels:
          - id: general
            label: general
            icon: Hash
            type: chat

        # ── Agents (apps) — fill these in as you build them ──────────────
        # Each agent lives under agents/<role>/{{SOUL.md,agents.yml,tools/}}.
        apps: {{}}

        # ── Plugins (Python modules contributing routes/cron/hooks) ──────
        # Bootstrap discovers each module + collects router/cron_executors/
        # startup_hooks/shutdown_hooks/middlewares.
        plugins:
          # Module path relative to where the process starts, which is this
          # directory — the Dockerfile's WORKDIR and the `cd` the scaffold
          # prints. A `tenants.<id>.` prefix would need a different working
          # directory, and could not import at all when the id contains a
          # hyphen, since that is not a valid Python module name.
          - plugins.health

        # ── Routines (file-as-truth scheduled work) — empty by default ───
        routines: {{}}
    """)


def _config_yaml() -> str:
    return dedent("""\
        # Tenant settings — editable from the workspace UI.

        opening_hours: {}
        phone: ""
        address: ""
    """)


def _routines_yml() -> str:
    return "# Agent-driven scheduled work. Each entry: cron + agent + prompt.\nroutines: {}\n"


def _example_plugin_health() -> str:
    return dedent('''\
        """Example plugin — exposes /api/health. Edit or replace.

        Bootstrap collects `router` from every plugin listed in
        workspace.yml#plugins and mounts them on the FastAPI app.
        """
        from fastapi import APIRouter

        router = APIRouter()


        @router.get("/api/health")
        async def health():
            return {"status": "ok"}
    ''')


def _npmrc() -> str:
    # Deliberately not a registry line. This used to scaffold
    # `registry=http://localhost:4873/` — the Verdaccio used to publish
    return dedent("""\
        # If you publish @runspace/ui to your own registry, point npm at it here:
        # registry=https://npm.example.internal/
    """)


def _dockerfile(tenant_id: str) -> str:
    return dedent(f"""\
        # {tenant_id} — runspace tenant
        # Build context: this directory.
        FROM python:3.12-slim

        WORKDIR /app

        COPY requirements.txt ./
        RUN pip install --no-cache-dir -r requirements.txt

        COPY . .

        ENV WORKSPACE_YML=/app/workspace.yml
        ENV TENANT_ID={tenant_id}
        ENV PORT=8000
        EXPOSE 8000

        CMD ["python", "-m", "runspace.workspace.serve"]
    """)


def _docker_compose(tenant_id: str) -> str:
    return dedent(f"""\
        services:
          api:
            container_name: {tenant_id}-api
            build: .
            ports:
              - "8000:8000"
            env_file:
              - .env
            restart: unless-stopped
    """)


def _readme(tenant_id: str, name: str) -> str:
    return dedent(f"""\
        # {name}

        Tenant scaffolded by `runspace init {tenant_id}`.

        ## Layout

        ```
        workspace.yml       workspace + plugin list (config-only path)
        plugins/            Python modules contributing routes/cron/hooks
        agents/             tenant agent code (SOUL.md + tools per role)
        routines.yml        scheduled work
        config.yaml         tenant settings (opening hours etc.)
        Dockerfile          extends runspace base; CMD runs workspace.serve
        ```

        ## Local development

        ```bash
        # Start a fresh tenant boot:
        python -m runspace.workspace.serve workspace.yml
        # or via docker:
        docker compose up
        ```

        ## Adding an agent

        1. Create `agents/<role>/SOUL.md` (the agent's persona + behaviour)
        2. Create `agents/<role>/agents.yml` (model + tool config)
        3. Add to `workspace.yml#apps:`:
           ```yaml
           apps:
             my_agent:
               name: Persona
               role: "Role description"
               soul: agents/<role>/SOUL.md
               tools: agents/<role>/tools/
               type: agentino  # or openclaw
           ```

        ## Adding a plugin (custom routes, cron, lifecycle hooks)

        1. Create `plugins/my_thing.py` with a `router = APIRouter()`
        2. Add `plugins.my_thing` to workspace.yml#plugins

        See `runspace/docs/24-architecture-review-2026-05.md` for the
        broader architecture.
    """)
